/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface NexanodeCard {
    config: string;
    content: string;
    footer: string;
    header: string;
  }
}
declare global {
  interface HTMLNexanodeCardElement
    extends Components.NexanodeCard,
      HTMLStencilElement {}
  var HTMLNexanodeCardElement: {
    prototype: HTMLNexanodeCardElement;
    new (): HTMLNexanodeCardElement;
  };
  interface HTMLElementTagNameMap {
    'nexanode-card': HTMLNexanodeCardElement;
  }
}
declare namespace LocalJSX {
  interface NexanodeCard {
    config?: string;
    content?: string;
    footer?: string;
    header?: string;
  }
  interface IntrinsicElements {
    'nexanode-card': NexanodeCard;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'nexanode-card': LocalJSX.NexanodeCard &
        JSXBase.HTMLAttributes<HTMLNexanodeCardElement>;
    }
  }
}
