name: Feat Branch CI

on:
  pull_request:
    branches:
      - feat/*

permissions:
  actions: read
  contents: read

jobs:
  feat-branch-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested

      # Cache node_modules
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn nx-cloud start-ci-run --distribute-on=".nx/workflows/dynamic-changesets.yaml" --stop-agents-after="build"
      - uses: nrwl/nx-set-shas@v4

      - run: git branch --track ${{ github.base_ref }} origin/${{ github.base_ref }}
        if: ${{ github.event_name == 'pull_request' }}

      - run: yarn nx affected -t lint test build
